### PR TITLE
fix(windows): gap in maximized undecorated window

### LINKED ISSUE #14025: [bug] Maximized window doesn't take up the entire screen space
### Describe the bug

This is Windows 10.

In the case of a window configured with decorations: false and transparent: true, and the taskbar option "Automatically hide the taskbar in desktop mode" is on, there is a 1px-ish gap next to the right border(see below) of a maximized tauri window, through which you can see part of the desktop background.

While "Automatically hide the taskbar in desktop mode" is off, the unexpected 1px-ish gap doesn't exist.

Position of the 1px-ish gap:

- taskbar at the bottom of the screen, the gap is at the right border;
- taskbar at the top of the screen, the gap is at the bottom border;
- taskbar at the left of the screen, no gap;
- taskbar at the right of the screen, the gap is at the bottom border;

Image

### Reproduction

1. configure the window as `decorations: false`, `transparent: true` in tauri.conf.json;
2. `pnpm tauri dev`;
3. maximize the window;
4. turn on "Automatically hide the taskbar in desktop mode" under System Settings -> Personalization -> Taskbar;

### Expected behavior

No 1px-ish gap.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 137.0.3296.93
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.89.0 (29483883e 2025-08-04)
    ✔ cargo: 1.89.0 (c24e10642 2025-06-23)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.15.0
    - pnpm: 8.6.9
    - npm: 9.5.0

[-] Packages
    - tauri 🦀: 2.7.0
    - tauri-build 🦀: 2.3.1
    - wry 🦀: 0.52.1
    - tao 🦀: 0.34.1
    - @tauri-apps/api : 2.0.0 (outdated, latest: 2.7.0)
    - @tauri-apps/cli : 2.0.0 (outdated, latest: 2.7.1)

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text

```

### Additional context

The problem happens on both Windows 10 and Windows 11.

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix https://github.com/tauri-apps/tauri/issues/14025

Fix maximized windows have empty edges when using auto hide task bar on Windows

### CODE REVIEW

File: src/platform_impl/windows/event_loop.rs [hunk 1]
```diff
@@ -2164,31 +2164,26 @@ unsafe fn public_window_callback_inner<T: 'static>(
...
-            let mut edges = 0;
-            for edge in [ABE_BOTTOM, ABE_LEFT, ABE_TOP, ABE_RIGHT] {
+            fn has_edge(edge: u32) -> bool {
               let mut app_data = APPBARDATA {
                 cbSize: std::mem::size_of::<APPBARDATA>() as _,
                 uEdge: edge,
                 ..Default::default()
               };
-              if SHAppBarMessage(ABM_GETAUTOHIDEBAR, &mut app_data) != 0 {
-                edges |= edge;
```
Comment (Legend-Master) [inline src/platform_impl/windows/event_loop.rs:2175]: The thing here is that `ABE_BOTTOM`, `ABE_LEFT`, ... are not bit flags, they're really just 0, 1, 2, 3 😂

**Review by amrbashir — APPROVED** [review]
