### PR TITLE
fix(windows): use registry value to detect dark mode

### LINKED ISSUE #8180: [bug] On Windows, the default app mode in custom color mode reverses the theme colors
### Describe the bug

Only when Windows is in `custom color mode`. Changing the `default app mode` will cause Tauri to use the opposite theme colors.

If the color mode is `Light` or `Dark`, then Tauri is also the corresponding theme color.

theme-color

### Reproduction

1. Windows colors: https://support.microsoft.com/en-us/windows/change-colors-in-windows-d26ef4d6-819a-581c-1581-493cfcc005fe#WindowsVersion=Windows_11
2. Select a custom color mode.
3. Try switching the default app mode and observe the title bar of the Tauri application.

### Expected behavior

Should match the theme color of the default app mode.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 119.0.2151.44
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - pnpm: 8.10.0
    - npm: 9.6.5

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

The registry can get the theme color used by the app:

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`

Default app mode: `AppsUseLightTheme`
Default windows mode: `SystemUsesLightTheme`

### PR DESCRIPTION
**Pull request by Slinetrac**
### Closes https://github.com/tauri-apps/tauri/issues/8180, related https://github.com/tauri-apps/tauri/issues/14693

https://github.com/user-attachments/assets/ad390ab1-62db-4743-b4be-79c27652c3e0

### CODE REVIEW

**Comment by Slinetrac** [comment]
Happy to get any feedback. cc @FabianLars @lucasfernog

**Comment by Legend-Master** [comment]
I can't seem to reproduce this on Windows 10 even before the fix 🤔

**Comment by Slinetrac** [comment]
> I can't seem to reproduce this on Windows 10 even before the fix 🤔

I haven’t tested this on Windows 10, but I can confirm that this issue can be reliably reproduced on Windows 11. It’s possible that Windows 10 and Windows 11 behave differently with respect to themes.

**Review by Legend-Master — APPROVED** [review]
Anyways, the code looks good to me, I still want wait and test this on a Windows 11 device to verify though

File: src/platform_impl/windows/dark_mode.rs [hunk 1]
```diff
@@ -218,6 +225,27 @@ fn should_apps_use_dark_mode() -> bool {
     .unwrap_or(false)
 }
 
+fn read_apps_use_light_theme() -> Option<bool> {
+  let mut data: u32 = 0;
+  let mut data_size = std::mem::size_of::<u32>() as u32;
+  let status = unsafe {
+    RegGetValueW(
+      HKEY_CURRENT_USER,
+      w!("Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize"),
```
Comment (Legend-Master) [inline src/platform_impl/windows/dark_mode.rs]:
```suggestion
      w!(r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"),
```

File: src/platform_impl/windows/dark_mode.rs [hunk 2]
```diff
@@ -199,6 +202,10 @@ fn should_use_dark_mode() -> bool {
 }
 
 fn should_apps_use_dark_mode() -> bool {
+  if let Some(apps_use_light_theme) = read_apps_use_light_theme() {
+    return !apps_use_light_theme;
+  }
+
   const UXTHEME_SHOULDAPPSUSEDARKMODE_ORDINAL: u16 = 132;
```
Comment (Legend-Master) [inline src/platform_impl/windows/dark_mode.rs:211]: Let's document the reason for this change here (e.g. this undocumented method `ShouldAppsUseDarkMode` may return wrong values here on Windows 11, and probably a link to this pull request)

**Review by Legend-Master — APPROVED** [review]
Tested on a Windows 11 machine (25H2, 26200.7462) and indeed this fixed the problem, also works well on my Windows 10 machine

Nice job, thanks! Just a few nitpicks and we're good to go

(also by the way, would you like to also upstream this change to [winit](https://github.com/rust-windowing/winit) as well? `tao` is a fork of it and we plan to switch back to it in the future, this seems to be reported there as well in https://github.com/rust-windowing/winit/issues/4161)

File: src/platform_impl/windows/dark_mode.rs (hunk 2 above)
Comment (Slinetrac) [reply src/platform_impl/windows/dark_mode.rs:211]: done

**Comment by Slinetrac** [comment]
> would you like to also upstream this change to [winit](https://github.com/rust-windowing/winit) as well? 

Happy to do that.
