### PR TITLE
fix(linux): Fix `Window::theme` may return incorrect theme

### LINKED ISSUE #799: `Window::theme` may return incorrect theme on Linux
**Describe the bug**

When setting a theme different from system settings at `WindowBuilder::with_theme`, a window created with the builder returns incorrect theme value by `Window::theme`. For example, when 'Light' is set to the system settings and 'Dark' is set to `WindowBuilder::with_theme`, the window's `Window::theme` returns `Theme::Light`.

**Steps To Reproduce**

1. Go to `Settings -> Appearance -> Style` and set 'Light' style
2. Run the following Rust code
3. Confirm the window is rendered with the dark theme
4. Check the `dbg!` output in the terminal window indicates that `Window::theme` returned `Theme::Light`

```rust
// Copyright 2014-2021 The winit contributors
// Copyright 2021-2023 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0

use tao::{
  event::{Event, WindowEvent},
  event_loop::{ControlFlow, EventLoop},
  window::WindowBuilder,
};

#[allow(clippy::single_match)]
fn main() {
  let event_loop = EventLoop::new();

  let mut window = Some(
    WindowBuilder::new()
      .with_title("A fantastic window!")
      .with_inner_size(tao::dpi::LogicalSize::new(300.0, 300.0))
      .with_min_inner_size(tao::dpi::LogicalSize::new(200.0, 200.0))
      .with_theme(Some(tao::window::Theme::Dark)) // Set Dark theme
      .build(&event_loop)
      .unwrap(),
  );

  dbg!(window.as_ref().unwrap().theme()); // Show the current theme

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;
    println!("{:?}", event);

    match event {
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        window_id: _,
        ..
      } => {
        // drop the window to fire the `Destroyed` event
        window = None;
      }
      Event::WindowEvent {
        event: WindowEvent::Destroyed,
        window_id: _,
        ..
      } => {
        *control_flow = ControlFlow::Exit;
      }
      Event::MainEventsCleared => {
        if let Some(w) = &window {
          w.request_redraw();
        }
      }
      _ => (),
    }
  });
}
```

Terminal output:

```
[examples/window.rs:25] window.as_ref().unwrap().theme() = Light
```

**Expected behavior**

Expected `dbg!()` output in terminal:

```
[examples/window.rs:25] window.as_ref().unwrap().theme() = Dark
```

**Screenshots**

screenshot

**Platform and Versions (please complete the following information):**
OS: Ubuntu 22.04
Rustc: 1.72
tao: 71d744cf90a6bcc5248561ec0f6f3a53a40e1fd9

**Would you want to assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Additional context**

Nothing

### PR DESCRIPTION
**Pull request by rhysd**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [x] This PR will resolve #799
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tao/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary
- [ ] It can be built on all targets and pass CI/CD.

### Other information

On Ubuntu 22.04, the default theme name is ["Yaru"](https://github.com/ubuntu/yaru) in both dark mode and light mode. So it is not possible to check the theme mode by suffix like "-dark". The only way I could come up with was remembering what theme was set on building the window and returning the value at `Window::theme`. This PR adopts the idea.

### CODE REVIEW

File: src/platform_impl/linux/window.rs [hunk 1]
```diff
@@ -773,15 +779,7 @@ impl Window {
   }
 
   pub fn theme(&self) -> Theme {
-    if let Some(settings) = Settings::default() {
-      let theme_name = settings.gtk_theme_name().map(|s| s.as_str().to_owned());
-      if let Some(theme) = theme_name {
-        if GTK_THEME_SUFFIX_LIST.iter().any(|t| theme.ends_with(t)) {
```
Comment (wusyong) [inline src/platform_impl/linux/window.rs:779]: If we choose to keep a theme state, we probably don't need this constant.
Can you remove `GTK_THEME_SUFFIX_LIST`'s definition as well?

Comment (amrbashir) [reply src/platform_impl/linux/window.rs:779]: We still need to check using `GTK_THEME_SUFFIX_LIST` because a developer may not specify an explicit theme to be set so it could be either light or dark but this PR implementation assumes that it will always be light theme.

File: src/platform_impl/linux/window.rs [hunk 2]
```diff
@@ -185,10 +186,14 @@ impl Window {
 
     let settings = Settings::default();
 
+    let mut theme = Theme::Light;
```
Comment (amrbashir) [inline src/platform_impl/linux/window.rs]: Instead of assuming that it is always light we should:
1. change the newly added `window.theme` to be `explicit_theme: Option<Theme>`
2. in the `Window.theme()` getter we check if `self.explicit_theme.unwrap_or_else(|| /* old logic here */)`

**Review by amrbashir — CHANGES_REQUESTED** [review]

File: src/platform_impl/linux/window.rs (hunk 2 above)
Comment (rhysd) [reply src/platform_impl/linux/window.rs]: OK, that also works in my use case. Since the configuration name is `preferred_theme`, I think it represents the field well. I'll update this branch.

Comment (rhysd) [reply src/platform_impl/linux/window.rs]: I applied the change at 1236933.

**Comment by rhysd** [comment]
I removed two redundant clones (`to_owned`) at 45a4a29ea39128b770433f04fc11421fd2b2423d.

**Comment by rhysd** [comment]
I removed two redundant clones (`to_owned`) at 94bf32546ab00b6b95d3926071dda88dffa53528.

**Review by amrbashir — APPROVED** [review]
