### PR TITLE
fix(macos): Fix color mappings in window.rs

### LINKED ISSUE #1127: Window background color is not properly set
**Describe the bug**
The background color of the window is not properly set as the window::RGBA (which is [u8;4]) is not properly converted to platform specific [0.0..=1.0; 4].

**Steps To Reproduce**
Set `with_background_color(RGBA::from[0x0f, 0x11, 0x16, 0xff])` on window builder. Optionally set the titlebar transparency to see the window color through it.

**Expected behavior**
Expected to have a nice dark background. Yet it becomes white.

**Screenshots**
Expected:
Image
Reality:
Image

**Platform and Versions (please complete the following information):**
OS: MacOS 15.5
Rustc: 1.88

**Additional context**
The issue is in the implementation of #995, that does not divide u8 values by 255.0. Does so for the alpha channel.

Image

Just adding the division manually into the tao source (`src/platform_impl/macos/window.rs`) and clean rebuild fixes the issue for me. I also see same issue in the other platforms src.

Why the alpha channel gets correctly normalized, but others do not?

### PR DESCRIPTION
**Pull request by aspcartman**
The color conversion from [u8;4] to [f64;4] was missing the division by 255.0. 

Fixes #1127.

### CODE REVIEW

File: src/platform_impl/android/ndk_glue.rs [hunk 1]
```diff
@@ -54,7 +54,7 @@ macro_rules! android_binding {
   };
   ($domain:ident, $package:ident, $activity:ident, $setup:path, $main:ident, $tao:path) => {{
     // NOTE: be careful when changing how this use statement is written
-    use $tao::{platform::android::prelude::android_fn, platform::android::prelude::*};
+    use $tao::platform::android::prelude::{android_fn, *};
```
Comment (amrbashir) [inline src/platform_impl/android/ndk_glue.rs]: @FabianLars please revert this change, last time I changed it, it broke usage in `wry` iirc

Comment (FabianLars) [reply src/platform_impl/android/ndk_glue.rs]: stupid muscle memory, i didn't want to do `git add .` 🙃 

is there an attribute like ts-ignore we can use to tell cargo not to format that?

Comment (amrbashir) [reply src/platform_impl/android/ndk_glue.rs]: looks like you found `#[rustfmt::skip]`,

maybe it is worth to add more context in the comment above stating what exactly breaks

Comment (FabianLars) [reply src/platform_impl/android/ndk_glue.rs]: maybe yeah, but i have no idea what's going on 😂

**Review by FabianLars — APPROVED** [review]
