### PR TITLE
fix(windows): fix appcrash on windows where darkmode is not supported

### LINKED ISSUE #11674: [bug] Tauri2 crashes immediately on Windows 10 LTSC 2016
### Describe the bug

Tauri2 is not starting on Windows 10 LTSC 2016. When executing the .exe it immediately terminates without any error message. When checking the Windows 10 EventLogs, the following Application Error is shown:

```
Faulting application name: tauri-app.exe, version: 0.1.0.0, time stamp: 0x6732271b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000
Faulting process id: 0x26ec
Faulting application start time: 0x01db344f7438982b
Faulting application path: C:\Users\Administrator\Desktop\TAURI\tauri-app.exe
Faulting module path: unknown
Report Id: cded0ad4-2365-481b-9e34-2c7c50b6831b
Faulting package full name: 
Faulting package-relative application ID: 
```

https://github.com/user-attachments/assets/1e5f7f1c-7c16-49c5-8612-e26f92f99353

### Reproduction

Create a new sample Project with: 

> cargo install create-tauri-app --locked
> cargo create-tauri-app

Build the Project: 

> cargo build

### Expected behavior

Tauri should start and open the sample GUI.

### Full `tauri info` output

```text
[✔] Environment                                                                                
    - OS: Windows 10.0.19045 x86_64 (X64)                                                      
    ✔ WebView2: 130.0.2849.80                                                                  
    ✔ MSVC:                                                                                    
        - Visual Studio Build Tools 2022                                                       
        - Visual Studio Professional 2022                                                      
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)                                                     
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)                                                     
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)                                                    
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN) 
    - node: 20.15.0                                                                            
    - npm: 10.7.0                                                                              
                                                                                               
[-] Packages                                                                                   
    - tauri 🦀: 2.1.1                                                                           
    - tauri-build 🦀: 2.0.3                                                                     
    - wry 🦀: 0.47.0                                                                            
    - tao 🦀: 0.30.7                                                                            
    - tauri-cli 🦀: 2.0.0-rc.16                                                                 
                                                                                               
[-] Plugins                                                                                    
    - tauri-plugin-shell 🦀: 2.0.2                                                              
                                                                                               
[-] App                                                                                        
    - build-type: bundle                                                                       
    - CSP: unset                                                                               
    - frontendDist: ../src
```

### Stack trace

_No response_

### Additional context

The exact same application is working fine on: 

- Windows 10 LTSC 2019
- Windows 10 LTSC 2021

### PR DESCRIPTION
**Pull request by Jnschrber**
The changes resolve this bug: https://github.com/tauri-apps/tauri/issues/11674 where Tauri2 crashes immediately on Windows 10 LTSC 2016

closes tauri-apps/tauri#11674

### CODE REVIEW

File: src/platform_impl/windows/dark_mode.rs [hunk 1]
```diff
@@ -79,10 +79,14 @@ pub fn allow_dark_mode_for_app(is_dark_mode: bool) {
   });
 
   if let Some(ver) = *WIN10_BUILD_VERSION {
+    // in case Windows 10 Build version < 18362, we have to call a special command (_allow_dark_mode_for_app)
     if ver < 18362 {
-      if let Some(_allow_dark_mode_for_app) = *ALLOW_DARK_MODE_FOR_APP {
-        unsafe { _allow_dark_mode_for_app(is_dark_mode) };
-      }
+        // but only call that command if the dark mode is supported...
+        if *DARK_MODE_SUPPORTED {
```
Comment (amrbashir) [inline src/platform_impl/windows/dark_mode.rs]: we could wrap the whole function in `if *DARK_MODE_SUPPORTED` similar to how it is done in `try_window_theme` function

**Review by amrbashir — CHANGES_REQUESTED** [review]
Thank you, could you also add a change file in `.changes` directory?

File: src/platform_impl/windows/dark_mode.rs (hunk 1 above)
Comment (Jnschrber) [reply src/platform_impl/windows/dark_mode.rs]: Hi,
please see my latest commit (https://github.com/tauri-apps/tao/pull/1022/commits/1f623298db2f59efcec3ee070b2a1c9dafe8e2ca), in which I have implemented your requested change.

**Review by amrbashir — APPROVED** [review]

File: .changes/dark-mode.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"tao": "patch"
+---
+
+Windows: Executing the function allow_dark_mode_for_app only if darkmode is supported.
```
Comment (amrbashir) [inline .changes/dark-mode.md]:
```suggestion
On Windows, fix crash on older windows versions that doesn't support dark mode.
```

**Review by amrbashir — APPROVED** [review]
