### PR TITLE
fix(linux): window can't be displayed on wayland, closes #503

### LINKED ISSUE #503: [bug] Window not showing on Wayland
Valid for all examples
tag: tao-v0.12.1 everything is normal
tag: tao-v0.13.0 window does not display, taskbar icons are created normally
Everything works fine in x11 mode (using `GDK_BACKEND=x11` environment variable)

Environment
  › OS: Arch Linux Rolling Release X64
  › DE: GNOME 42.3 + Wayland
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

### PR DESCRIPTION
**Pull request by wusyong**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: src/platform_impl/linux/window.rs [hunk 1]
```diff
@@ -152,8 +152,10 @@ impl Window {
     // https://docs.gtk.org/gtk3/drawing-model.html
     window.set_app_paintable(true);
     let widget = window.upcast_ref::<gtk::Widget>();
-    unsafe {
-      gtk::ffi::gtk_widget_set_double_buffered(widget.to_glib_none().0, 0);
+    if !event_loop_window_target.is_wayland() {
```
Comment (amrbashir) [inline src/platform_impl/linux/window.rs:155]: should probably leave a TODO comment, or is this not needed on wayland?

**Review by amrbashir — APPROVED** [review]

File: src/platform_impl/linux/window.rs (hunk 1 above)
Comment (wusyong) [reply src/platform_impl/linux/window.rs:155]: If it's just a window then it's not needed. For GL painting, I haven't done testing it yet. So we could just leave it.
