### PR TITLE
fix: maximizing window on linux, closes #442

### LINKED ISSUE #442: [bug] Positioning window with config does not work under certain conditions
> This issue has been upstreamed from https://github.com/tauri-apps/tauri/issues/4445 

### Describe the bug

Positioning the window at the top-left works with this very config:
```
"windows": [
      {
        "x": 0.0,
        "y": 0.0,
        "height": 1080,
        "width": 1980,
        "title": "John Doe",
        "maximized": true,
        "decorations": true
      }
    ]
```
But as soon as I set `"resizable": false` the window positioning does not work which means the window is not at [0,0].
image
Also, funnily, when I disable `maximization` and enable `resizability` the window is only slighty (~5px) misplaced.

### Reproduction

1. Create a project with tauri cli 1.0.0
2. Try config as shown above

### Expected behavior

Place window correctly in all cases

### Platform and versions

```shell
Environment
  › OS: Manjaro 21.3.0 X64
  › Node.js: 18.3.0
  › npm: 8.5.5
  › pnpm: 7.2.0
  › yarn: 1.22.11
  › rustup: 1.24.3
  › rustc: 1.63.0-nightly
  › cargo: 1.63.0-nightly
  › Rust toolchain: nightly-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3333/
  › framework: Vue.js

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

Gnome: 42.2
Windowing-System: X11
SO: Manjaro
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by keiya01**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: src/platform_impl/linux/window.rs [hunk 1]
```diff
@@ -184,6 +184,7 @@ impl Window {
     if attributes.maximized {
       window.maximize();
     }
+    window.set_resizable(attributes.resizable);
```
Comment (amrbashir) [inline src/platform_impl/linux/window.rs]: `window.set_resizable` is already called on Line 81, how does adding this fixes the issue?

Comment (keiya01) [reply src/platform_impl/linux/window.rs]: oh I forgot to remove this line...

Comment (keiya01) [reply src/platform_impl/linux/window.rs]: I removed it.
https://github.com/tauri-apps/tao/pull/456/commits/b726e310ab3c4c991010911b3d0b0335def03e03

Comment (amrbashir) [reply src/platform_impl/linux/window.rs]: do you know if this also fixes #302

Comment (keiya01) [reply src/platform_impl/linux/window.rs]: I don't know but I will test it

Comment (keiya01) [reply src/platform_impl/linux/window.rs]: I tested https://github.com/tauri-apps/tao/issues/302 in this PR, but this behavior is not occurred in initial build.
So I think this is occurred only in runtime.

**Comment by amrbashir** [comment]
Just tried this PR and the bug still exists

Here is my repro:
````rs
// Copyright 2019-2021 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0

use tao::{
  event::{Event, WindowEvent},
  event_loop::{ControlFlow, EventLoop},
  window::WindowBuilder,
};

#[allow(clippy::single_match)]
fn main() {
  let event_loop = EventLoop::new();

  let mut window = Some(
    WindowBuilder::new()
      .with_title("A fantastic window!")
      .with_inner_size(tao::dpi::LogicalSize::new(1080, 1980))
      .with_maximized(true)
      .with_resizable(false)
      .build(&event_loop)
      .unwrap(),
  );

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;
    println!("{:?}", event);

    match event {
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        window_id: _,
        ..
      } => {
        // drop the window to fire the `Destroyed` event
        window = None;
      }
      Event::WindowEvent {
        event: WindowEvent::Destroyed,
        window_id: _,
        ..
      } => {
        *control_flow = ControlFlow::Exit;
      }
      Event::MainEventsCleared => {
        if let Some(w) = &window {
          w.request_redraw();
        }
      }
      _ => (),
    }
  });
}
```

**Comment by keiya01** [comment]
@amrbashir 
I fixed the above error. Please check the following commit 🙇
https://github.com/tauri-apps/tao/pull/456/commits/c3267711ccbba71a081c52a29a795d4db6d6cd10

**Comment by amrbashir** [comment]
the last commit brought more issues than it solved. If you you set the size to `100,200` and set resizable to false and maximized to true, it will fill the whole screen which it shouldn't.

Here is some scenarios with the expected outcome to help you debug this further:
- ```json
	{
		"width": 100,
		"height": 200,
		"resizable": true,
		"maximized": true,
	}
   ```
   the window should open maximized but when you unmaximize it, it should restore its size to 100, 200 and the window can be resized using the mouse
  
- ```json
	{
		"width": 100,
		"height": 200,
		"resizable": false,
		"maximized": true,
	}
   ```
   the window should open maximized but when you unmaximize it, it should restore its size to 100, 200 and the window can NOT be resized using the mouse

- ```json
	{
		"width": 100,
		"height": 200,
		"resizable": true,
		"maximized": false,
	}
   ```
   the window should NOT open maximized and its size should be 100, 200 and can be resized using the mouse

- ```json
	{
		"width": 100,
		"height": 200,
		"resizable": false,
		"maximized": false,
	}
   ```
   the window should NOT open maximized and its size should be 100, 200 and can NOT be resized using the mouse

**Comment by keiya01** [comment]
@amrbashir 
Thank you for your help 🙏
 
> If you you set the size to 100,200 and set resizable to false and maximized to true, it will fill the whole screen which it shouldn't.

Please tell me about the above sentence.
I think my latest commit is filling window with `resizable: false` and `maximized: true`, but shouldn't we fill window in this senario?

**Comment by keiya01** [comment]
And I forgot to fix maximization in runtime, so I will fix it...

**Comment by amrbashir** [comment]
> I think my latest commit is filling window with resizable: false and maximized: true, but shouldn't we fill window in this senario?

My bad I mixed them up. While I was testing, I had resizable true and maximized false and it maximized the window which it shouldn't.

just try to match the 4 scenarios I posted above with the expected outcome while creating the window and in runtime.

**Comment by keiya01** [comment]
> My bad I mixed them up. While I was testing, I had resizable true and maximized false and it maximized the window which it shouldn't.

In my environment, when I had resizable true and maximized false, the window is not maximized.
Is this case occurred in runtime?

**Comment by amrbashir** [comment]
No, it was when creating the window. I'll do more testing tomorrow.

**Comment by amrbashir** [comment]
I did some more testing and noted down the issues I found below but I am not sure if these are bugs or the desired behavior.

|maximized | resizable | |
| ---  | --- | --- |
|true  | true  | works perfectly |
|false | true  | works perfectly |
|true  | false | can't be UNmaximized at runtime |
|false | false | can't be maximized at runtime |

**Comment by keiya01** [comment]
Thank you for your investigation. Yeah I'm fixing runtime behavior.
And I think `maximized true and resizable false` senario should work but I will check if this senario works on other platform.

**Comment by keiya01** [comment]
I tested these cases on macOS and windows.
On macOS these are working great but on windows these are not working...
But I think `maximized: true, resizable: false` should work because this is easy to understand intuitively.

**Review by amrbashir — APPROVED** [review]
I think this PR is good enough but will let @wusyong decide whether he want to merge or not

**Comment by keiya01** [comment]
Do we need to support maximizing window on windows at initialization?
If you agree, I will fix it in another PR.
